/**
* File was generated by animation packager.
*/
#ifndef		_FONT_COMBO_I6_H
#define		_FONT_COMBO_I6_H


#define		FONT_COMBO_I6_NUM_MODULES				11
#define		FONT_COMBO_I6_MODULE_4				1


#define		FONT_COMBO_I6_NUM_FRAMES				26
#define		FONT_COMBO_I6_FRAME_SPACE				0
#define		FONT_COMBO_I6_FRAME_0				15
#define		FONT_COMBO_I6_FRAME_1				16
#define		FONT_COMBO_I6_FRAME_2				17
#define		FONT_COMBO_I6_FRAME_3				18
#define		FONT_COMBO_I6_FRAME_4				19
#define		FONT_COMBO_I6_FRAME_5				20
#define		FONT_COMBO_I6_FRAME_6				21
#define		FONT_COMBO_I6_FRAME_7				22
#define		FONT_COMBO_I6_FRAME_8				23
#define		FONT_COMBO_I6_FRAME_9				24
#define		FONT_COMBO_I6_FRAME_LEVEL				25


#define		FONT_COMBO_I6_NUM_ANIMS				0


#endif