/**
* File was generated by animation packager.
*/
#ifndef		_FONT_TITLE_SMALL_200_H
#define		_FONT_TITLE_SMALL_200_H


#define		FONT_TITLE_SMALL_200_NUM_MODULES				94


#define		FONT_TITLE_SMALL_200_NUM_FRAMES				94


#define		FONT_TITLE_SMALL_200_NUM_ANIMS				0


#endif