/**
* File was generated by animation packager.
*/
#ifndef		_FONT_MISSION_01_I6_H
#define		_FONT_MISSION_01_I6_H


#define		FONT_MISSION_01_I6_NUM_MODULES				95


#define		FONT_MISSION_01_I6_NUM_FRAMES				96


#define		FONT_MISSION_01_I6_NUM_ANIMS				0


#endif