/**
* File was generated by animation packager.
*/
#ifndef		_FONT_ADVERT_H
#define		_FONT_ADVERT_H


#define		FONT_ADVERT_NUM_MODULES				0


#define		FONT_ADVERT_NUM_FRAMES				0


#define		FONT_ADVERT_NUM_ANIMS				0


#endif