/**
* File was generated by animation packager.
*/
#ifndef		_HUD_TUT_01_I6_H
#define		_HUD_TUT_01_I6_H


#define		HUD_TUT_01_I6_NUM_MODULES				19
#define		HUD_TUT_01_I6_MODULE_2				0
#define		HUD_TUT_01_I6_MODULE_MIENG2				1
#define		HUD_TUT_01_I6_MODULE_4_1				2
#define		HUD_TUT_01_I6_MODULE_5_1				3
#define		HUD_TUT_01_I6_MODULE_CIRCLE				4
#define		HUD_TUT_01_I6_MODULE_MIENG1				5
#define		HUD_TUT_01_I6_MODULE_1				6
#define		HUD_TUT_01_I6_MODULE_10				7
#define		HUD_TUT_01_I6_MODULE_11				8
#define		HUD_TUT_01_I6_MODULE_3				9
#define		HUD_TUT_01_I6_MODULE_3A				10
#define		HUD_TUT_01_I6_MODULE_9				11
#define		HUD_TUT_01_I6_MODULE_7				12
#define		HUD_TUT_01_I6_MODULE_5_2				13
#define		HUD_TUT_01_I6_MODULE_12				14
#define		HUD_TUT_01_I6_MODULE_4_2				15
#define		HUD_TUT_01_I6_MODULE_6				16
#define		HUD_TUT_01_I6_MODULE_8				17
#define		HUD_TUT_01_I6_MODULE_MIENG2				18


#define		HUD_TUT_01_I6_NUM_FRAMES				16
#define		HUD_TUT_01_I6_FRAME_CIRCLE				0
#define		HUD_TUT_01_I6_FRAME_MIENG1				1
#define		HUD_TUT_01_I6_FRAME_MIENG2				2
#define		HUD_TUT_01_I6_FRAME_1				3
#define		HUD_TUT_01_I6_FRAME_2				4
#define		HUD_TUT_01_I6_FRAME_3				5
#define		HUD_TUT_01_I6_FRAME_3A				6
#define		HUD_TUT_01_I6_FRAME_4				7
#define		HUD_TUT_01_I6_FRAME_5				8
#define		HUD_TUT_01_I6_FRAME_6				9
#define		HUD_TUT_01_I6_FRAME_7				10
#define		HUD_TUT_01_I6_FRAME_8				11
#define		HUD_TUT_01_I6_FRAME_9				12
#define		HUD_TUT_01_I6_FRAME_10				13
#define		HUD_TUT_01_I6_FRAME_11				14
#define		HUD_TUT_01_I6_FRAME_12				15


#define		HUD_TUT_01_I6_NUM_ANIMS				0


#endif