/**
* File was generated by animation packager.
*/
#ifndef		_HUD_01_I6_H
#define		_HUD_01_I6_H


#define		HUD_01_I6_NUM_MODULES				1
#define		HUD_01_I6_MODULE_SLOW				0


#define		HUD_01_I6_NUM_FRAMES				1
#define		HUD_01_I6_FRAME_SLOWDOWN				0


#define		HUD_01_I6_NUM_ANIMS				1
#define		HUD_01_I6_ANIM_BAY				0


#endif