/**
* File was generated by animation packager.
*/
#ifndef		_HUD_02_I6_H
#define		_HUD_02_I6_H


#define		HUD_02_I6_NUM_MODULES				6
#define		HUD_02_I6_MODULE_READY				0
#define		HUD_02_I6_MODULE_3				1
#define		HUD_02_I6_MODULE_2				2
#define		HUD_02_I6_MODULE_1				3
#define		HUD_02_I6_MODULE_SOUND_NORMAL				4
#define		HUD_02_I6_MODULE_SOUND_CLOSE				5


#define		HUD_02_I6_NUM_FRAMES				10
#define		HUD_02_I6_FRAME_READY				0
#define		HUD_02_I6_FRAME_3				1
#define		HUD_02_I6_FRAME_2				2
#define		HUD_02_I6_FRAME_1				3
#define		HUD_02_I6_FRAME_SOUND_LOCK				4
#define		HUD_02_I6_FRAME_SOUND_NORMAL				5
#define		HUD_02_I6_FRAME_SOUND_SELECT				6
#define		HUD_02_I6_FRAME_SOUND_CLOSE_LOCK				7
#define		HUD_02_I6_FRAME_SOUND_CLOSE_NORMAL				8
#define		HUD_02_I6_FRAME_SOUND_CLOSE_SELECT				9


#define		HUD_02_I6_NUM_ANIMS				8
#define		HUD_02_I6_ANIM_SOUND_LOCK				0
#define		HUD_02_I6_ANIM_SOUND_NM				1
#define		HUD_02_I6_ANIM_SOUND_SELECT				2
#define		HUD_02_I6_ANIM_SOUND_ACTIVE				3
#define		HUD_02_I6_ANIM_CLOSE_LOCK				4
#define		HUD_02_I6_ANIM_CLOSE_NM				5
#define		HUD_02_I6_ANIM_CLOSE_SELECT				6
#define		HUD_02_I6_ANIM_CLOSE_ACTIVE				7


#endif