/**
* File was generated by animation packager.
*/
#ifndef		_OBJECT_CIRCLE_01_I6_H
#define		_OBJECT_CIRCLE_01_I6_H


#define		OBJECT_CIRCLE_01_I6_NUM_MODULES				1
#define		OBJECT_CIRCLE_01_I6_MODULE_C				0


#define		OBJECT_CIRCLE_01_I6_NUM_FRAMES				1
#define		OBJECT_CIRCLE_01_I6_FRAME_CIRCLE				0


#define		OBJECT_CIRCLE_01_I6_NUM_ANIMS				0


#endif