/**
* File was generated by animation packager.
*/
#ifndef		_PINE_ADVERT_H
#define		_PINE_ADVERT_H


#define		PINE_ADVERT_NUM_MODULES				0


#define		PINE_ADVERT_NUM_FRAMES				0


#define		PINE_ADVERT_NUM_ANIMS				0


#endif